### PR TITLE
Added proprietary Silva/Nexus/Garmin sentences for displaying perform…

### PR DESCRIPTION
**Pull request by joabakk**
…ance data from Signal K

Is there any way to add a short description after each check box?

### CODE REVIEW

**Comment by tkurki** [comment]
You can add a `title` property, see for example https://github.com/SignalK/signalk-zones/blob/master/index.js#L27-L29

**Comment by joabakk** [comment]
Yes that will overwrite the title of the check box, say APB. I would like to add a short description of what the sentence does after the bold name. Much like the description of the plugin itself.
image

**Comment by tkurki** [comment]
Not without extra effort.

**Comment by joabakk** [comment]
The screenshot is from that commit. I added description, but it does not appear. Also tried subtitle:
I'm a decent googler, but don't know what search terms to use for the plugin webpages

**Comment by joabakk** [comment]
a6bd64c is a quick fix so the user knows what the sentences are

**Pull request merged**
