### PR TITLE
Add missing brackets in the example

### PR DESCRIPTION
**Pull request by FredericGuilbault**

### CODE REVIEW

**Comment by tkurki** [comment]
That configuration snippet is valid (well, as valid as a snippet is) but you have pipedProvider that consists of a single serialport provider, meaning that there is nothing that converts the serialport input to Signal K, which 99.9% of the time is incorrect.

The README dates from the time with SK server having no admin ui to speak of and inputs were configured by editing settings files.

Now we have the admin ui, so a better example here would be a screen shot of the relevant part of it. Care to make one?

**Comment by FredericGuilbault** [comment]
Ah oui,
I get it now. I must say it's confusing ...to the point I tought it was an error lol. 

But then, I have read https://github.com/SignalK/signalk-to-nmea0183/issues/11 
And as I understand, this snippet does not reflect intended use of `signalk-to-nmea`. This plugin emit tcp on port 10110. But the snippet seem to be  about  producing a fake serial device/port in `/dev/`.  There is an other plugin for serial devices If I remember. 

Prior to updating the README I just want to make sure about that. Then ill make a proposal with an updated screen shot.

**Comment by tkurki** [comment]
The configuration snippet is about the case where you want to output the sentences to a serial connection. The plugin itself only output events, that are used by default by tcp connection on port 10110. If you want serial output you need to configure the serial to handle the event as well.

**Comment by FredericGuilbault** [comment]
Im still a but confused so Im not sure if I got it right. Tell me if something need to be changed. IDC making an other revision.

**Comment by tkurki** [comment]
I updated the readme in 001c27971e1e5d7579f1758ae5df7c3e5d435b41.

**Pull request closed without merging**
